#!/bin/sh
mkdir -p /tmp/tailscale
/var/runtime/tailscaled --tun=userspace-networking --socks5-server=localhost:1055 &
until /var/runtime/tailscale up --authkey=${TAILSCALE_AUTHKEY} --hostname=aws-lambda-app
do
    sleep 0.1
done
echo Tailscale started

if [ -z "${AWS_LAMBDA_RUNTIME_API}" ]; then
  exec env ALL_PROXY="socks5://localhost:1055/" /usr/local/bin/aws-lambda-rie /var/lang/bin/python3.6 -m awslambdaric $@
else
  exec env ALL_PROXY="socks5://localhost:1055/" /var/lang/bin/python3.6 -m awslambdaric $@
fi     
